version: "3.8"
services:
  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysql_db:3306/todo_table?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username": "root",
        "spring.datasource.password": "19971007",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    depends_on:
      - mysql_db
    links:
      - mysql_db:todo_table
  mysql_db:
    image: mysql:8.0
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: todo_table
      MYSQL_ROOT_PASSWORD: 19971007